config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :members
  resources :employees
  resources :companies
  namespace :assignment do
    resources :todo_lists
  end
  mount Ckeditor::Engine => '/ckeditor'

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: 'blazer'
  end

  # 聊天室
  resources :room_messages
  resources :rooms

  root 'admin/lab_forums#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]

      get 'ping', to: 'base#ping'
      get 'ping_auth', to: 'base#ping_auth'
      get 'info', to: 'base#info'

      resources :ideas
    end
  end

  # 履歷
  get 'resume', to: 'resume#show'

  # 版型收編
  get 'card', to: 'card#show'
  get 'testimonial', to: 'testimonial#show'

  # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
  get '/:single_page', to: 'staticpages#show', as: 'page'

  devise_for :users, module: 'auth'

  namespace :admin do
    resources :lab_forums do
      resources :comments
      get 'status', on: :member

      resources :likes, only: :create
    end

    resources :question_types, except: :show
    resources :member_login_histories, only: :index
  end

  namespace :assignment do
    resources :todos do
      get 'status', on: :member
    end

    resources :items_imports, only: %i[new create] do
      get 'excel_template', on: :collection
    end
  end

  # get 'bmi', to: 'bmi#index'
  # post 'bmi', to: 'bmi#result'

  # get 'name', to: 'name#index'
  # post 'name', to: 'name#post_result'
  # get 'username', to: 'name#get_result'
  #

  mount Sidekiq::Web => '/sidekiq'
end

app/models/employee.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: employees
#
#  id           :bigint           not null, primary key
#  first_name   :string(255)
#  last_name    :string(255)
#  phone_number :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  company_id   :bigint
#
# Indexes
#
#  index_employees_on_company_id  (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#
class Employee < ApplicationRecord
  belongs_to :company, touch: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company, presence: true

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:company_id, :last_name, :first_name, :phone_number)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :company %>
    <%= f.input :last_name %>
    <%= f.input :first_name %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.company %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.phone_number %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @employee.company %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employee.phone_number %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>