config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :members
  resources :employees
  resources :companies
  namespace :assignment do
    resources :todo_lists
  end
  mount Ckeditor::Engine => '/ckeditor'

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: 'blazer'
  end

  # 聊天室
  resources :room_messages
  resources :rooms

  root 'admin/lab_forums#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]

      get 'ping', to: 'base#ping'
      get 'ping_auth', to: 'base#ping_auth'
      get 'info', to: 'base#info'

      resources :ideas
    end
  end

  # 履歷
  get 'resume', to: 'resume#show'

  # 版型收編
  get 'card', to: 'card#show'
  get 'testimonial', to: 'testimonial#show'

  # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
  get '/:single_page', to: 'staticpages#show', as: 'page'

  devise_for :users, module: 'auth'

  namespace :admin do
    resources :lab_forums do
      resources :comments
      get 'status', on: :member

      resources :likes, only: :create
    end

    resources :question_types, except: :show
    resources :member_login_histories, only: :index
  end

  namespace :assignment do
    resources :todos do
      get 'status', on: :member
    end

    resources :items_imports, only: %i[new create] do
      get 'excel_template', on: :collection
    end
  end

  # get 'bmi', to: 'bmi#index'
  # post 'bmi', to: 'bmi#result'

  # get 'name', to: 'name#index'
  # post 'name', to: 'name#post_result'
  # get 'username', to: 'name#get_result'
  #

  mount Sidekiq::Web => '/sidekiq'
end

app/models/assignment.rb
module Assignment
  def self.table_name_prefix
    'assignment_'
  end
end

app/models/assignment/todo_list.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: todo_lists
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TodoList < ApplicationRecord
  has_many :tasks, dependent: :destroy

  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }
  # accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/controllers/assignment/base_controller.rb
# frozen_string_literal: true

module Assignment
  class BaseController < ApplicationController
    layout 'assignment'
  end
end

app/controllers/assignment/items_imports_controller.rb
# frozen_string_literal: true

module Assignment
  class ItemsImportsController < BaseController
    skip_before_action :verify_authenticity_token

    def new
      @items_import = ItemsImport.new
    end

    # https://medium.com/@JasonCodes/ruby-on-rails-importing-from-excel-1504fd99a35e
    #
    # Ruby on Rails 4 - CSV import - no implicit conversion into string
    # https://stackoverflow.com/questions/30395750/ruby-on-rails-4-csv-import-no-implicit-conversion-into-string/30395981
    #
    def create
      @sheet_val = ImportSheets::Promotion.new(self.class, items_import_params[:file].path).sty_flow.to_json
      AddEndangeredWorker.perform_async(@sheet_val)

      respond_to do |format|
        format.js
        format.json { render json: @sheet_val.to_json }
      end
    end

    def excel_template
      @template = [
        { content: "'2631146634002" },
        { content: "'2633001796009" },
        { content: "'2631142373004" }
      ]

      respond_to do |format|
        format.xlsx
      end
    end

    private

    def items_import_params
      params.require(:items_import).permit(:file)
    end
  end
end

app/controllers/assignment/todo_lists_controller.rb
# frozen_string_literal: true

module Assignment
  class TodoListsController < BaseController
    before_action :set_todo_list, only: %i[show edit update destroy]

    def index
      @todo_lists = TodoList.all
    end

    def show; end

    def new
      @todo_list = TodoList.new
    end

    def edit; end

    def create
      @todo_list = TodoList.new(todo_list_params)

      respond_to do |format|
        if @todo_list.save
          format.html { redirect_to [:assignment, @todo_list], notice: 'Todo list was successfully created.' }
          format.json { render :show, status: :created, location: @todo_list }
        else
          format.html { render :new }
          format.json { render json: @todo_list.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @todo_list.update(todo_list_params)
          format.html { redirect_to [:assignment, @todo_list], notice: 'Todo list was successfully updated.' }
          format.json { render :show, status: :ok, location: @todo_list }
        else
          format.html { render :edit }
          format.json { render json: @todo_list.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @todo_list.destroy
      respond_to do |format|
        format.html { redirect_to assignment_todo_lists_url, notice: 'Todo list was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      # params.require(:assignment_todo_list).permit(:name)
      # params.require(:todo_list)
      #       .permit(:name, tasks_attributes: [:id, :_destroy, :todo_list_id, :name, :completed, :due])
      params.require(:todo_list)
            .permit(:name, tasks_attributes: Task.attribute_names.map(&:to_sym).push(:_destroy))
    end
  end
end

app/controllers/assignment/todolists_controller.rb
class Assignment::TodolistsController < ApplicationController
  # layout "admin"

  before_action :find_todos, only: %i[edit update destroy show status]
  # before_action :authenticate_user!

  # 若非後台人員，即會出現登入阻擋
  # before_action :required

  def index
    # @todos = current_user.todos.all.order(id: :desc) unless current_user.todos
    @todos = Todo.where(user: current_user).order(id: :desc)
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user

    if @todo.save
      redirect_to todolists_path, notice: I18n.t('notice.create_success')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @todo.destroy if @todo
    redirect_to todolists_path, notice: I18n.t('notice.deleted')
  end

  def update
    if @todo.update(todo_params)
      redirect_to todolists_path, notice: I18n.t('notice.update_success')
    else
      render :edit
    end
  end

  def status
    @id = params[:id]

    if @todo.status.eql? false
      @todo.update(status: true)
    else
      @todo.update(status: false)
    end

    respond_to do |format|
      format.js { render 'status' }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:content, :complete_time, :status, :priority)
  end

  def find_todos
    @todo = Todo.find_by(id: params[:id])
  end
end

app/controllers/assignment/todos_controller.rb
# frozen_string_literal: true

module Assignment
  class TodosController < BaseController
    before_action :find_todos, only: %i[edit update destroy show status]
    before_action :authenticate_user!

    # 若非後台人員，即會出現登入阻擋
    # before_action :required

    def index
      # @todos = current_user.todos.all.order(id: :desc) unless current_user.todos
      @todos = Todo.where(user: current_user).order(id: :desc)

      respond_to do |format|
        format.html
        format.xlsx
      end
    end

    def new
      @todo = Todo.new
    end

    def create
      @todo = Todo.new(todo_params)
      @todo.user = current_user

      if @todo.save
        redirect_to assignment_todos_path, notice: I18n.t('notice.create_success')
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def destroy
      @todo&.destroy
      redirect_to assignment_todos_path, notice: I18n.t('notice.deleted')
    end

    def update
      if @todo.update(todo_params)
        redirect_to assignment_todos_path, notice: I18n.t('notice.update_success')
      else
        render :edit
      end
    end

    def status
      @id = params[:id]

      if @todo.status.eql? false
        @todo.update(status: true)
      else
        @todo.update(status: false)
      end

      respond_to do |format|
        format.js { render 'status' }
      end
    end

    private

    def todo_params
      params.require(:todo).permit(:content, :complete_time, :status, :priority)
    end

    def find_todos
      @todo = Todo.find_by(id: params[:id])
    end
  end
end

app/helpers/assignment/todo_lists_helper.rb
# frozen_string_literal: true

module Assignment::TodoListsHelper
  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: 'add_fields ' + args[:class], data: { id: id, fields: fields.gsub("\n", '') })
  end
end

app/helpers/assignment/todos_helper.rb
module Assignment::TodosHelper
  def complete_time(time)
    return 'None' if time.eql? nil

    time
  end
end

app/views/assignment/todo_lists/_form.html.erb
<%= simple_form_for([:assignment, @todo_list]) do |f| %>
  <%= f.error_notification %>

  <div class="row mb-2">
    <div class="card col-md-12 card-primary card-outline">
      <div class="card-header">
        <h3 class="card-title">任務牆</h3>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-6"></div>
        </div>
        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.input :name %>
            </div>
          </div>

          <div class="col-sm"></div>

          <div class="col-sm-2">
            <label class="string optional" for="btn_name">新增任務❤️</label>
            <%= link_to_add_row('Add Task', f, :tasks, class: 'btn btn-primary form-control string') %>
          </div>
        </div>

        <br />

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <table class='table'>
                <thead>
                  <tr>
                    <th></th>
                    <th>Completed</th>
                    <th>Task Name</th>
                    <th>Due</th>
                  </tr>
                </thead>
                <tbody class='fields'>
                  <%= f.simple_fields_for :tasks do |builder| %>
                    <%= render 'task', f: builder %>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="btn-group">
        <%= f.button :submit, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/assignment/todo_lists/_task.html.erb
<tr>
  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to (fa_icon 'trash'), '#', class: 'remove_record' %>
  </td>
  <td><%= f.input :completed, label: false, :as => :select %></td>
  <td><%= f.input :name, label: false %></td>
  <td>
    <div class="input-group" data-target-input="nearest">
      <%= f.text_field :due, id: "complete_time",
                             class: "form-control datepicker",
                             data: { target: '#complete_time'},
                             value: f.object.due %>
      <div class="input-group-append" data-target="#complete_time" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </td>
</tr>

app/views/assignment/todo_lists/edit.html.erb
<%= stylesheet_link_tag 'assignment/todo_lists' %>

<div class="container">
  <h1>Editing Todo List</h1>
  <%= render 'form', todo_list: @todo_list %>
  <%= link_to 'Show', [:assignment, @todo_list] %> |
  <%= link_to 'Back', assignment_todo_lists_path %>
</div>

app/views/assignment/todo_lists/index.html.erb
<div class="container">
  <h1>Todo Lists</h1>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @todo_lists.each do |todo_list| %>
        <tr>
          <td><%= todo_list.name %></td>
          <td>
            <%= link_to (fa_icon 'search'), [:assignment, todo_list] %>
            <%= link_to (fa_icon 'pencil'), edit_assignment_todo_list_path(todo_list) %>
            <%= link_to (fa_icon 'trash'), [:assignment, todo_list], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New List', new_assignment_todo_list_path %>
</div>

app/views/assignment/todo_lists/new.html.erb
<div class="container">
  <h1>New List</h1>
  <%= render 'form', todo_list: @todo_list %>
  <%= link_to 'Back', assignment_todo_lists_path, class: 'btn' %>
</div>

app/views/assignment/todo_lists/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @todo_list.name %>
  </p>

  <%= link_to 'Edit', edit_assignment_todo_list_path(@todo_list) %> |
  <%= link_to 'Back', assignment_todo_lists_path %>
</div>