config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :members
  resources :employees
  resources :companies
  namespace :assignment do
    resources :todo_lists
  end
  mount Ckeditor::Engine => '/ckeditor'

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: 'blazer'
  end

  # 聊天室
  resources :room_messages
  resources :rooms

  root 'admin/lab_forums#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]

      get 'ping', to: 'base#ping'
      get 'ping_auth', to: 'base#ping_auth'
      get 'info', to: 'base#info'

      resources :ideas
    end
  end

  # 履歷
  get 'resume', to: 'resume#show'

  # 版型收編
  get 'card', to: 'card#show'
  get 'testimonial', to: 'testimonial#show'

  # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
  get '/:single_page', to: 'staticpages#show', as: 'page'

  devise_for :users, module: 'auth'

  namespace :admin do
    resources :lab_forums do
      resources :comments
      get 'status', on: :member

      resources :likes, only: :create
    end

    resources :question_types, except: :show
    resources :member_login_histories, only: :index
  end

  namespace :assignment do
    resources :todos do
      get 'status', on: :member
    end

    resources :items_imports, only: %i[new create] do
      get 'excel_template', on: :collection
    end
  end

  # get 'bmi', to: 'bmi#index'
  # post 'bmi', to: 'bmi#result'

  # get 'name', to: 'name#index'
  # post 'name', to: 'name#post_result'
  # get 'username', to: 'name#get_result'
  #

  mount Sidekiq::Web => '/sidekiq'
end

app/models/company.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: companies
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :employees, dependent: :destroy

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of employees</th>
      <th colspan="3">action</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.employees.count %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<% if @company.employees.any? %>
<h1>Employees</h1>

<table class="table">
  <thead>
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Phone Number</th>
    </tr>
  </thead>

  <tbody>
    <% @company.employees.each do |employee| %>
      <tr>
        <td><%= employee.last_name %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>