config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :members
  resources :employees
  resources :companies
  namespace :assignment do
    resources :todo_lists
  end
  mount Ckeditor::Engine => '/ckeditor'

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: 'blazer'
  end

  # 聊天室
  resources :room_messages
  resources :rooms

  root 'admin/lab_forums#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :names, only: [:create]

      get 'ping', to: 'base#ping'
      get 'ping_auth', to: 'base#ping_auth'
      get 'info', to: 'base#info'

      resources :ideas
    end
  end

  # 履歷
  get 'resume', to: 'resume#show'

  # 版型收編
  get 'card', to: 'card#show'
  get 'testimonial', to: 'testimonial#show'

  # 基本routes應用：https://railsbook.tw/chapters/11-routes.html
  get '/:single_page', to: 'staticpages#show', as: 'page'

  devise_for :users, module: 'auth'

  namespace :admin do
    resources :lab_forums do
      resources :comments
      get 'status', on: :member

      resources :likes, only: :create
    end

    resources :question_types, except: :show
    resources :member_login_histories, only: :index
  end

  namespace :assignment do
    resources :todos do
      get 'status', on: :member
    end

    resources :items_imports, only: %i[new create] do
      get 'excel_template', on: :collection
    end
  end

  # get 'bmi', to: 'bmi#index'
  # post 'bmi', to: 'bmi#result'

  # get 'name', to: 'name#index'
  # post 'name', to: 'name#post_result'
  # get 'username', to: 'name#get_result'
  #

  mount Sidekiq::Web => '/sidekiq'
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_rooms_on_name  (name) UNIQUE
#

class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
  <h1>
    Editing room <%= @room.name %>
  </h1>

  <%= render partial: 'form' %>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-3">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="alert alert-primary">
        <h4 class="alert-heading">
          Welcome to my chatroom!
        </h4>

        <hr />

        <p>
          <a href="https://iridakos.com/programming/2019/04/04/creating-chat-application-rails-websockets">
            Reference Link
          </a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container">
  <h1>
    Creating a room
  </h1>

  <%= render partial: 'form' %>
</div>

app/views/rooms/show.html.erb
<div class="container">

  <h1>
    <%= @room.name %>
  </h1>

  <div class="row">
    <div class="col-12 col-md-3">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
        <% @room_messages.each do |room_message| %>
          <div class="chat-message-container">
            <div class="row no-gutters">
              <div class="col-auto text-center">
                <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
              </div>

              <div class="col">
                <div class="message-content">
                  <p class="mb-1">
                    <%= room_message.message %>
                  </p>

                  <div class="text-right">
                    <small>
                      <%= room_message.created_at %>
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= simple_form_for @room_message, remote: true do |form| %>
        <div class="input-group mb-3">
          <%= form.input :message, as: :string,
                                  wrapper: false,
                                  label: false,
                                  input_html: {
                                    class: 'chat-input',
                                    autocomplete: 'off'
                                  } %>
          <div class="input-group-append">
            <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
          </div>
        </div>

        <%= form.input :room_id, as: :hidden %>
      <% end %>
    </div>
  </div>

  <div class="d-none" data-role="message-template">
    <div class="chat-message-container">
      <div class="row no-gutters">
        <div class="col-auto text-center">
          <img src="" class="avatar" alt="" data-role="user-avatar">
        </div>

        <div class="col">
          <div class="message-content">
            <p class="mb-1" data-role="message-text">

            </p>

            <div class="text-right">
              <small data-role="message-date">
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>